//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mona.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public Nullable<int> students { get; set; }
        public Nullable<int> disciplin { get; set; }
    
        public virtual Disciplin Disciplin1 { get; set; }
        public virtual Students Students1 { get; set; }
    }
}
