//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mona.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Molochnikov11Entities : DbContext
    {
        public Molochnikov11Entities()
            : base("name=Molochnikov11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplin> Disciplin { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<марка_автомобиля> марка_автомобиля { get; set; }
        public virtual DbSet<Покупатели> Покупатели { get; set; }
        public virtual DbSet<Продажа_автомобилей> Продажа_автомобилей { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<viduslugy> viduslugy { get; set; }
        public virtual DbSet<Квартиросъёмщики1> Квартиросъёмщики1 { get; set; }
        public virtual DbSet<Коммунальные_услуги1> Коммунальные_услуги1 { get; set; }
    }
}
