//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mona.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.Продажа_автомобилей = new HashSet<Продажа_автомобилей>();
        }
    
        public int Код_автомобиля { get; set; }
        public string Название_автомобиля { get; set; }
        public int Марка { get; set; }
        public System.DateTime Год_производства { get; set; }
        public string Цвет { get; set; }
        public string Категория { get; set; }
        public string Цена { get; set; }
    
        public virtual марка_автомобиля марка_автомобиля { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажа_автомобилей> Продажа_автомобилей { get; set; }
    }
}
