//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mona.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Коммунальные_услуги1
    {
        public int @int { get; set; }
        public string ФИО { get; set; }
        public string domadress { get; set; }
        public string nomercheta { get; set; }
        public string kolvo { get; set; }
        public string skvart { get; set; }
        public string viduskugi { get; set; }
        public string counton1metr { get; set; }
        public string counton1man { get; set; }
    }
}
